app/core/views.py
from flask import render_template, redirect, flash, url_for, request, g, jsonify, Blueprint
from flask_login import login_user, login_required, logout_user, current_user, current_app

from app import my_login_manager as login_manager
from .forms import LoginForm, RegistrationForm
from .models import Agent, Order
from ..setting import STATIC_FOLDER_PATH, TEMPLATE_FOLDER_PATH


my_blueprint = Blueprint(
    'kursach', __name__,
    url_prefix='/course_project',
    template_folder=TEMPLATE_FOLDER_PATH,
    static_folder=STATIC_FOLDER_PATH,
    static_url_path='/static'
    )


@my_blueprint.before_request
def all_order():
    current_app.jinja_env.globals['all_orders'] = Order.all_order()
    current_app.jinja_env.globals['all_free_orders'] = Order.all_free_order()


@my_blueprint.route('/', methods=['GET', 'POST'])
@my_blueprint.route('/index/', methods=['GET', 'POST'])
def index():
    return render_template('kursach/index.html', methods=['GET'])


@login_manager.user_loader
def load_user(user_id):
    return Agent.query.get(int(user_id))


@my_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in")
        return redirect(url_for('index'))
    login_form = LoginForm()
    if request.method == "POST":
        if login_form.validate_on_submit():
            user = Agent.get_user(login_form.login.data, login_form.password.data)
            if user is not None:
                login_user(user, login_form.remember_me.data)
                flash('Login success')
                return redirect(request.args.get('next') or url_for('kursach.index'))
            else:
                flash('Current user not exist')
    return render_template('kursach/login.html', title='Sing in', form=login_form)


@my_blueprint.route('/registration', methods=['GET', 'POST'])
def registration():
    if current_user.is_authenticated:
        flash("You are already logged in")
        return redirect(url_for('kursach.index'))
    reg_form = RegistrationForm()
    if request.method == "POST":
        if reg_form.validate_on_submit():
            registration_user = Agent.add_user(
                reg_form.login.data, reg_form.password.data, reg_form.username.data,
                reg_form.surname.data, reg_form.specialization.data, reg_form.email.data, reg_form.rank.data
            )
            if registration_user is True:
                user = Agent.get_user(reg_form.login.data, reg_form.password.data)
                login_user(user)
                return redirect(request.args.get('next') or url_for('index'))
            else:
                flash("User already exist or incorrect data")
    return render_template('kursach/registration.html', title='Registration', form=reg_form)


@my_blueprint.before_request
def before_request():
    g.user = current_user


@my_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    return redirect(url_for('kursach.index'))


@my_blueprint.route('/my_orders', methods=['GET'])
@login_required
def my_orders():
    orders = Agent.db_call_proc('get_order', [current_user.id])
    return render_template('kursach/my_orders.html', title='My orders', orders_list=orders)


@my_blueprint.route('/new_orders', methods=['GET', 'POST'])
@login_required
def new_orders():
    new_order = Agent.db_call_proc('get_new_order')
    return render_template('kursach/new_orders.html', title='New order', orders=new_order)


@my_blueprint.route('/add_order', methods=['POST'])
def add_order():
    add_request = request.get_json(force=True)
    order_id = add_request['id']
    query = Agent.confirm_oder(order_id, g.user.id)
    if query is True:
        return jsonify({'answer': 'Order successfully added'})
    else:
        return jsonify({'answer': 'Error'})


@my_blueprint.route('/add_new_order', methods=['GET', 'POST'])
def add_new_order():
    order_form = Order.select_all_select_field()
    if order_form.validate_on_submit():
        new_order = Order.insert_order(order_form.address.data, order_form.town.data[0], order_form.ghost.data[0])
        if new_order:
            flash("Order successful added")
            return redirect(request.args.get('next') or url_for('kursach.index'))
        else:
            flash("Error please try again")
            return redirect(url_for("kursach.add_new_order"))
    return render_template('kursach/add_new_order.html', form=order_form)

app/templates/kursach/add_new_order.html
{% extends "kursach/index.html" %}
{% block content %}
    <form class="form-horizontal" method="post" name="ghost_order">
        <div class="container">
            <h2>Add ghost order</h2>
            {{form.hidden_tag()}}
            <p>
                Please choose town:<br>
                {{form.town}}<br>
                {% for error in form.errors.town %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}<br>
                Please enter address:<br>
                {{form.address}}<br>
                {% for error in form.errors.address %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}<br>
                Please choose ghost type:<br>
                {{form.ghost}}<br>
                {% for error in form.errors.ghost %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}<br>
            </p>
            <p><input type="submit" value="Add new order"></p>
        </div>
    </form>
{% endblock %}

app/templates/kursach/index.html
<!DOCTYPE html>
<html lang="en">
<meta charset="utf-8">
<link type="text/css" rel="stylesheet" href="{{ url_for('kursach.static', filename='css/bootstrap.min.css') }}">
<link rel="shortcut icon" href="{{ url_for('kursach.static', filename='favicon.ico') }}">
<head>
    {% if title %}
        <title>{{title}} - kursach</title>
    {% else %}
        <title>Kursach</title>
    {% endif %}
</head>
<body>
<div class="pull-right col-md-2">
    <img src="{{ url_for('kursach.static', filename='ghostbusters_logo-svg.png') }}" class="img-thumbnail" width="150" height="150">
</div>
<div class="container">
    <div class="navbar navbar-static-top col-md-10">
        <a class="navbar-brand" href="#">Kursach</a>
        <div class="pull-right">
            {% if current_user.is_authenticated %}
                <p>Hi {{ (current_user.name, current_user.surname) | join(", ") }}!<p> All current orders: {{ all_orders }}, all free orders: {{ all_free_orders }}
            {% endif %}
        </div>
    </div>
    <div class="navbar-inner col-md-10">
        <ul class="nav nav-tabs">
            <li><a href="{{ url_for('kursach.index') }}">Home</a></li>
            {% if current_user.is_authenticated %}
                <li><a href="{{ url_for('kursach.logout') }}">Logout</a></li>
                <li><a href="{{ url_for('kursach.my_orders') }}">My orders</a></li>
                <li><a href="{{ url_for('kursach.new_orders') }}">New orders</a></li>
            {% endif %}
            {% if not current_user.is_authenticated%}
                <li><a href="{{ url_for('kursach.login') }}">Login</a></li>
                <li><a href="{{ url_for('kursach.registration') }}">Registration</a></li>
                <li><a href="{{ url_for('kursach.add_new_order') }}">Add order</a></li>
            {% endif %}
        </ul>
    </div>
</div>
<div class="container">
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul>
                {% for message in messages %}
                    <li>{{ message }} </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    {% block content %}
    {% endblock %}
</div>
</body>
<script src="{{ url_for('kursach.static', filename='js/jquery-2.2.3.min.js') }}"></script>
<script src="{{ url_for('kursach.static', filename='js/bootstrap.min.js') }}"></script>
<script src="{{ url_for('kursach.static', filename='js/add_order.js') }}"></script>
</html>

app/templates/kursach/login.html
{% extends "kursach/index.html" %}
{% block content %}
    <form class="form-horizontal" method="post" name="login">
        <div class="container">
            <h2>Sign In</h2>
            {{form.hidden_tag()}}
            <div>
                Please enter your login:<br>
                {{form.login(size=25)}}<br>
                {% for error in form.errors.login %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
        <div>
                Please enter your password:<br>
                {{form.password}}<br>
                {% for error in form.errors.password %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
        </div>
            <p>{{form.remember_me}} Remember Me</p>
            <p><input type="submit" value="Sign In"></p>
        </div>
    </form>
{% endblock %}

app/templates/kursach/my_orders.html
{% extends "kursach/index.html" %}
{% block content %}
    {% for order in orders_list %}
        <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12">
            <h3>Order</h3>
            <p>Town - {{order.town}}</p>
            <p>Address - {{order.address}}</p>
            <p>Type - {{order.ghost_type}}</p>
            <p>Dangerous - {{order.dangerous}}</p>
        </div>
    {% endfor %}
{% endblock%}

app/templates/kursach/new_orders.html
{% extends "kursach/index.html" %}
{% block content %}
    {% for order in orders %}
        <div class="col-md-4 col-lg-4 col-sm-6 col-xs-12" id="order{{order.id}}">
            <h3>New Order</h3>
            <p>Town - {{order.town}}</p>
            <p>Address - {{order.address}}</p>
            <p>Type - {{order.ghost_type}}</p>
            <p>Dangerous - {{order.dangerous}}</p>
            <p id="answer{{order.id}}">Not added</p>
            <button id="result{{order.id}}" onclick="add_order('{{order.id}}')">Take order</button>
        </div>
    {% endfor %}
{% endblock%}

app/templates/kursach/registration.html
{% extends "kursach/index.html" %}
{% block content %}
{#    <script src="../static/js/"></script>#}
    <form class="form-horizontal" method="post" name="registration">
        <div class="container">
            <h2>Registration</h2>
            {{form.hidden_tag()}}
            <div>
                Please enter your login:<br>
                {{form.login(min=4, max=25)}}<br>
                {% for error in form.errors.login %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div id="password">
                Please enter your password:<br>
                {{form.password()}}<br>
                {% for error in form.errors.password %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div id="repeat_pass">
                Please repeat password:<br>
                {{form.confirm()}}<br>
                {% for error in form.errors.confirm %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
                Please enter your username:<br>
                {{form.username(size=35)}}<br>
                {% for error in form.errors.username %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
                Please enter your surname:<br>
                {{form.surname(size=35)}}<br>
                {% for error in form.errors.surname %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
                Please enter your specialization:<br>
                {{form.specialization()}}<br>
                {% for error in form.errors.specialization %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
                Please enter your email adress:<br>
                {{form.email()}}<br>
                {% for error in form.errors.email %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
                Please enter your rank:<br>
                {{form.rank()}}<br>
                {% for error in form.errors.rank %}
                    <span style="color: red;">[{{error}}]</span>
                {% endfor %}
            </div>
            <div>
            <input type="submit" value="Registration">
            </div>
        </div>
    </form>
{% endblock %}